### ISSUE TITLE
Super simple UI

### ISSUE THREAD

**Issue by fourgrant** [riggsmarkham/GolfTeams#3]
Riggs - sometimes when I'm at the course I need to quickly make new teams via my phone. 

It's always a case of DELETING a player and running it again. I generally (aka NEVER) have added someone at the course. I could maybe see needing that in the future, but I don't need it now. 

At it's most easiest (?) if I could edit the .csv in the browser and run the script and get the UI to show me teams, that'd be great. 

Just throwing that out there to see if you have time and interest. 

Thanks!

**Comment by riggsmarkham** [comment]
Ok, so I do have a pretty bare bones website in riggsmarkham.com, so I think I could make another page on there and add this as its backend.

The plan would be to have to have it have the csv in the backend (uploaded on the server running my website), and then each player would have a "playing vs. "not playing" toggle next to their name. And then you click a button to generate a new set of teams.

Eventually I'd also have it where you can replace the current csv on file with a new one (to update the average scores for each player), but that might take a bit more work.

(This would also work if you needed somebody else to run it)

**Comment by fourgrant** [comment]
That sounds good. I would have to periodically update their averages on my
laptop which is no problem at all.

Cool! Thanks.

**Comment by riggsmarkham** [comment]
Already off to a good start on it

![image](https://user-images.githubusercontent.com/13248949/134025598-88876b9b-72c3-4dbe-9ae2-bd20204c469e.png)

Need to code the player selector next

And then a big "upload updated file" button

**Comment by riggsmarkham** [comment]
So... it's done and up on [my website](https://riggsmarkham.com/golf_teams), but the buttons don't seem to work on mobile for me, so I'll have to figure out what's going on there.

**Comment by fourgrant** [comment]
Cool! Thanks.

**Comment by riggsmarkham** [comment]
Done. So, you can use [riggsmarkham.com/golf_teams](https://riggsmarkham.com/golf_teams) to do everything from now on. If you want to select or deselect players, hit the "Modify Players" button, then check/uncheck the players and hit "Update Active Players" to save it. If you want to update the averages for each player, now you'll use a csv file that looks like:  
```
Name,Average
Andy,42.2
Ben C.,42.7
Ben H.,40.7
Benton,41.5
Bill S.,41.8
Billie W.,37.1
Bruce S,44.8
```
And to upload that file, hit "Modify Players" and then upload it with the Upload Player Data button. Then, finally, to generate the teams, put a number in Max Teams and then hit the "Generate New Set of Teams" button and a table containing your teams will pop up.

I know it'll be hard to use on the phone, but UI is really hard and I'm pretty bad at it, so y'all will just have to deal.

**Comment by fourgrant** [comment]
Cool! So I upload the CSV from home using this and then modify on the
course if needed? Not sure I can manipulate and upload a new CSV from my
Iphone.

**Comment by riggsmarkham** [comment]
Yep. If you upload a csv it'll stay on there until the next time you upload something (or if the server restarts for some reason). And any changes you make to the active players will also persist until you change it again, upload a file, or the server restarts. No need to deal with any csv files on your phone.
